/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bust.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/bust.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={1} decay={2} color="#6fb7ff" position={[1.464, 3.438, 0.065]} />
      <spotLight intensity={3.96} angle={0.231} penumbra={0.82} decay={2} color="#400040" position={[-1.06, 11.6, 8.58]} target={nodes.SpotLight.target}>
        <primitive object={nodes.SpotLight.target} position={[0, 0, -1]} />
      </spotLight>
      <directionalLight intensity={1} decay={2} position={[5.98, 4.074, -1.46]} target={nodes.DirectionalLight.target}>
        <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
      </directionalLight>
      <pointLight intensity={1} decay={2} color="#1cff8d" position={[2.032, 1.303, 0]} />
      <pointLight intensity={1} decay={2} color="#ff0f0f" position={[2.069, 1.98, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.earLeft} position={[0, 1.993, -0.837]} rotation={[-Math.PI / 2, 1.107, -0.248]} scale={[-1.06, 0.44, 0.8]} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.earRight} position={[0, 1.993, 0.837]} rotation={[Math.PI / 2, -1.107, -0.248]} scale={[1.06, 0.44, 0.8]} />
      <mesh geometry={nodes.Torus.geometry} material={materials.nose} position={[0.552, 1.832, 0]} rotation={[-Math.PI / 2, -0.251, 0]} scale={[0.76, 0.32, 0.88]} />
      <mesh geometry={nodes.Capsule.geometry} material={materials.head} position={[0.109, 2.194, 0]} rotation={[0, 0, 0.185]} scale={[0.98, 0.84, 0.84]} />
      <mesh geometry={nodes.Torus_1.geometry} material={materials.jaw} position={[0.379, 1.53, 0]} rotation={[-Math.PI / 2, 0.133, 0]} scale={[0.7, 0.56, 0.92]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.shoulderLeft} position={[0, 0.172, -0.984]} scale={0.5} />
      <mesh geometry={nodes.Sphere_1.geometry} material={materials.shoulderRight} position={[0, 0.172, 0.984]} scale={0.5} />
      <mesh geometry={nodes.Capsule_1.geometry} material={materials.sternum} position={[0.01, 0.147, 0]} scale={[-0.7, 0.42, 1.44]} />
      <mesh geometry={nodes.Lathe.geometry} material={materials.traprezoid} position={[0, 0.247, 0]} scale={[1.36, 2.04, 2.64]} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[0, 0.799, 0]} scale={[0.46, 1.8, 0.38]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} rotation={[Math.PI / 2, 0, 0]} scale={[2, 1, 5]} />
      <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[-0.228, 2.302, 0]} scale={[0.84, 1, 0.86]} />
    </group>
  )
}

useGLTF.preload('/bust.gltf')
